const $=id=>document.getElementById(id);let results=[];let controller=null;let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')}};
function ipToNum(ip){const p=ip.trim().split('.').map(Number);if(p.length!==4||p.some(x=>!Number.isInteger(x)||x<0||x>255))throw Error('IP inválido');return (((p[0]*256)+p[1])*256+p[2])*256+p[3]}
function numToIp(n){return [n>>>24,(n>>>16)&255,(n>>>8)&255,n&255].join('.')}
function setStatus(t){$('status').textContent=t}
function addResult(r){results.push(r);if(results.length===1)$('resultsBody').innerHTML='';const tr=document.createElement('tr');tr.innerHTML=`<td>${r.ip}</td><td>${r.port}</td><td class="${r.open?'open':'closed'}">${r.open?'ABERTA':'FECHADA'}</td><td>${r.ms} ms</td>`;$('resultsBody').appendChild(tr);$('tested').textContent=results.length;if(r.open){$('openPorts').textContent=results.filter(x=>x.open).length;$('ips').textContent=new Set(results.filter(x=>x.open).map(x=>x.ip)).size}}
$('startBtn').onclick=async()=>{let a,b,ps,pe,timeout;try{a=ipToNum($('ipStart').value);b=ipToNum($('ipEnd').value);ps=+$('portStart').value;pe=+$('portEnd').value;timeout=+$('timeout').value;if(a>b)throw Error('IP inicial deve ser menor ou igual ao IP final');if(ps<1||pe>65535||ps>pe)throw Error('Faixa de portas inválida');if(pe-ps>9999)throw Error('Limite: no máximo 10000 portas por faixa')}catch(e){setStatus(e.message);return}
results=[];$('resultsBody').innerHTML='<tr><td colspan="4" class="empty">Escaneando...</td></tr>';$('ips').textContent='0';$('openPorts').textContent='0';$('tested').textContent='0';$('startBtn').disabled=true;$('stopBtn').disabled=false;controller=new AbortController();
try{const res=await fetch('/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({startIp:numToIp(a),endIp:numToIp(b),startPort:ps,endPort:pe,timeout}),signal:controller.signal});if(!res.ok)throw Error('Serviço local não respondeu corretamente');const reader=res.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const lines=buf.split('\n');buf=lines.pop();for(const line of lines){if(!line.trim())continue;const item=JSON.parse(line);if(item.type==='result')addResult(item);if(item.type==='status')setStatus(item.message);if(item.type==='done')setStatus('Scan concluído.')}}}catch(e){if(e.name==='AbortError')setStatus('Scan interrompido.');else setStatus('Erro: '+e.message)}finally{$('startBtn').disabled=false;$('stopBtn').disabled=true;controller=null}}
$('stopBtn').onclick=()=>{if(controller)controller.abort()};$('exportBtn').onclick=()=>{if(!results.length)return;const csv='IP,Porta,Status,Tempo(ms)\n'+results.map(r=>`${r.ip},${r.port},${r.open?'ABERTA':'FECHADA'},${r.ms}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='scan-rede.csv';a.click();URL.revokeObjectURL(a.href)};
$('auditBtn').onclick=()=>{const result=auditCredential($('auditUser').value,$('auditPass').value);const finding=result.findings.length?`<ul>${result.findings.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p>Nenhum problema comum encontrado nesta avaliação local.</p>';const box=$('auditResult');box.className='auditResult '+(result.level==='FORTE'?'auditStrong':result.level==='MÉDIA'?'auditMedium':'auditWeak');box.innerHTML=`<strong>${result.level}</strong> — pontuação ${result.score}/100 ${finding}`};
$('clearAuditBtn').onclick=()=>{$('auditUser').value='';$('auditPass').value='';$('auditResult').className='auditResult empty';$('auditResult').textContent='Nenhuma auditoria realizada.'};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
