const http=require('http');const fs=require('fs');const path=require('path');const net=require('net');
const PORT=8787,ROOT=__dirname;
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
function ipNum(ip){const p=ip.split('.').map(Number);return (((p[0]*256+p[1])*256+p[2])*256+p[3])>>>0}function ipText(n){return [n>>>24,(n>>>16)&255,(n>>>8)&255,n&255].join('.')}
function testPort(ip,port,timeout){return new Promise(resolve=>{const started=Date.now(),s=new net.Socket();let done=false;const finish=open=>{if(done)return;done=true;s.destroy();resolve({open,ms:Date.now()-started})};s.setTimeout(timeout);s.once('connect',()=>finish(true));s.once('timeout',()=>finish(false));s.once('error',()=>finish(false));s.connect(port,ip)})}
async function scan(body,res){let a,b,ps,pe,timeout;try{a=ipNum(body.startIp);b=ipNum(body.endIp);ps=Number(body.startPort);pe=Number(body.endPort);timeout=Math.min(5000,Math.max(100,Number(body.timeout)||500));if(a>b||b-a>1023||ps<1||pe>65535||ps>pe||pe-ps>9999)throw Error('Parâmetros inválidos');}catch(e){res.writeHead(400,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:e.message}))}
res.writeHead(200,{'Content-Type':'application/x-ndjson; charset=utf-8','Cache-Control':'no-cache','Access-Control-Allow-Origin':'*'});let tested=0;for(let n=a;n<=b;n++){const ip=ipText(n);res.write(JSON.stringify({type:'status',message:`Testando ${ip}...`})+'\n');for(let port=ps;port<=pe;port++){const r=await testPort(ip,port,timeout);tested++;res.write(JSON.stringify({type:'result',ip,port,open:r.open,ms:r.ms})+'\n');if(res.flushHeaders)res.flushHeaders()} }res.write(JSON.stringify({type:'done',tested})+'\n');res.end()}
const server=http.createServer((req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST'});return res.end()}if(req.method==='POST'&&req.url==='/scan'){let data='';req.on('data',c=>{data+=c;if(data.length>100000)req.destroy()});req.on('end',()=>{try{scan(JSON.parse(data),res)}catch(e){res.writeHead(400);res.end(JSON.stringify({error:'JSON inválido'}))}});return}let reqPath=req.url.split('?')[0];if(reqPath==='/')reqPath='/index.html';const file=path.normalize(path.join(ROOT,reqPath));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});
server.listen(PORT,'127.0.0.1',()=>console.log(`Scanner de Rede IP: http://127.0.0.1:${PORT}`));
